name: "Block Autosquash Commits"
description: "Prevent merging pull requests that contain commit messages prefixed with fixup! or squash!"
author: "xt0rted"
branding:
  icon: "alert-circle"
  color: "Red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true

runs:
  using: "node12"
  image: "dist/main.js"
