name: "Block Autosquash Commits"

description: "Prevent merging pull requests that contain commit messages prefixed with fixup! or squash!"

author: "xt0rted"

branding:
  icon: "alert-circle"
  color: "red"

inputs:
  repo-token:
    description: "GITHUB_TOKEN token or a repo scoped PAT"
    required: true
    default: ${{ github.token }}

runs:
  using: "docker"
  image: "Dockerfile"
